// Generated by Wrangler on Sat May 18 2024 12:25:58 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  AUDIOLOGGER_URL: "https://audiologger.westeurope.cloudapp.azure.com";
}
