#:schema node_modules/wrangler/config-schema.json
name = "zwfm-gemistplayer"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-03-29"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist"
